import React from "react"

const columns = [
    { field: "orderid", headerName: "Order ID" ,width: 200,},
    { field: "category", headerName: "Category" ,width: 150, sortable:false},
    { field: "brand", headerName: "Brand" ,width: 150,sortable:false},
    { field: "buyertype", headerName: "Buyer Type" ,width: 150,sortable:false},
    { field: "payment", headerName: "Payment",width: 200 },
    { field: "returnreason", headerName: "Return Reason" ,width: 200,sortable:false},
    { field: "additionalcomment", headerName: "Additional Comment",width: 310 },
    { field: "returnmoney", headerName: "Return",width: 130 ,sortable:false,type:'boolean'},
    { field: "replacement", headerName: "Replace" ,width: 140,sortable:false,type:'boolean'},
    { field: "status", headerName: "Status",width: 130,sortable:false },
  ];
  const rows = [
    {
      id:1,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "687",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: true,
      replacement: false,
      status: "Warehouse",
    },
    {
      id:2,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "687",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: true,
      replacement: false,
      status: "Warehouse",
    },
    {
      id:3,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "687",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: true,
      replacement: false,
      status: "Warehouse",
    },
    {
      id:4,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "687",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: false,
      replacement: true,
      status: "Warehouse",
    },
    {
      id:5,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "6867",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: false,
      replacement: true,
      status: "Warehouse",
    },
    {
      id:6,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "1687",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: true,
      replacement: false,
      status: "Warehouse",
    },
    {
      id:7,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "6872",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: true,
      replacement: false,
      status: "Warehouse",
    },
    {
      id:8,
      orderid: 1983470230,
      category: "Clothing",
      brand: "Puma",
      buyertype: "Retailer",
      payment: "6827",
      returnreason: "Out of Stock",
      additionalcomment: "The item will be restocked in a few days",
      returnmoney: false,
      replacement: true,
      status: "Warehouse",
    },
  ];

  export {columns,rows}